### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by lasagnamassage** [ashaunthomas/CS220Project#1]
We currently need artwork for:
-Normal Paddle select icon
-Brick select icon
-Lucille (barbed wire bat) select icon
- in-game sprites for all the paddles

**Comment by lasagnamassage** [comment]
Also, icons for the powerups (make them however, you're really good!):
- Decoy ball 
- Pistol
- Vector Warp
- Slow
- Speed Up
- Steal (Opponents Power-Up)

**Comment by ashaunthomas** [comment]
[https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjE0OzO-bHMAhXnsYMKHa8gC44QjRwIBw&url=http%3A%2F%2Fwww.redbubble.com%2Fpeople%2Fevpoe%2Fworks%2F12957326-the-walking-dead-negan-and-lucille%3Fp%3Dposter&psig=AFQjCNFw9fGNaSTBJgPohwyPIGFom7gOfQ&ust=1461954082886511](neegan)

**Comment by lasagnamassage** [comment]
Neegan inspiration: 
![image](https://cloud.githubusercontent.com/assets/11917290/14896724/9917b1be-0d44-11e6-9eba-aac34bef91ff.png)

**Comment by Kysetopher** [comment]
![normal paddle](https://cloud.githubusercontent.com/assets/17969780/14904851/3d4674a6-0d71-11e6-9384-79f41ff6a5aa.png)

**Comment by Kysetopher** [comment]
![lucielle](https://cloud.githubusercontent.com/assets/17969780/14904858/48cb4054-0d71-11e6-952b-9e43e2f4ccc2.png)

**Comment by Kysetopher** [comment]
![brick paddle](https://cloud.githubusercontent.com/assets/17969780/14904859/4ba228f6-0d71-11e6-9a9e-ba8bd2f22c33.png)

**Comment by lasagnamassage** [comment]
yessss!

**Comment by lasagnamassage** [comment]
We just need the powerup icons!

**Comment by Kysetopher** [comment]
![shadowclonejutsu](https://cloud.githubusercontent.com/assets/17969780/14944701/3bdc005c-0fc1-11e6-8932-f1fccd76ac87.png)
![slow](https://cloud.githubusercontent.com/assets/17969780/14944702/3da498ae-0fc1-11e6-8d99-34d2c6b7eaf2.png)
![speed](https://cloud.githubusercontent.com/assets/17969780/14944703/3eee3b0c-0fc1-11e6-9d41-0b65e954807f.png)
![steal](https://cloud.githubusercontent.com/assets/17969780/14944704/40000ade-0fc1-11e6-9726-13c47034d37b.png)
![vector swap](https://cloud.githubusercontent.com/assets/17969780/14944705/40de1f22-0fc1-11e6-98da-d5d964c3b0da.png)
![gun](https://cloud.githubusercontent.com/assets/17969780/14944706/41da85a0-0fc1-11e6-9c39-efc731d8cf7b.png)

**Comment by Kysetopher** [comment]
![powerup icon](https://cloud.githubusercontent.com/assets/17969780/14944725/b6d7ab6c-0fc1-11e6-9630-70728b31dd97.png)
looks like its all white but its not

**Comment by Kysetopher** [comment]
or it is but the backround is black

**Comment by lasagnamassage** [comment]
Well done man, we're set
